- src/containers/Projects/CreateProjectPopup/index.js
> CUR-401 Fix Thumbnail URL

- src/containers/H5PPreview.js
- src/containers/Preview/PlaylistPreview/ActivityShared.js
- src/helpers/xapi.js
It initialize xAPI calls for H5P
> Cur 637 xapi statements

- src/containers/Account/ProfilePage.js
- src/containers/Account/style.scss
> [CUR-673] organzization types are added to user account information 

- src/containers/LMS/GoogleClassroom/Activity/index.js
Added extra check for interactions that dont generate xapi statements at all
> CUR-768 Bugfix

- src/containers/LMS/GoogleClassroom/Activity/index.js
> disable turnin popup for IB

- src/containers/LMS/GoogleClassroom/Activity/index.js
removed IB check from turn-in popup
> removed IB check from turn-in popup

- src/helpers/xapi.js
> fix platform error

- src/containers/LMS/GoogleClassroom/Activity/index.js
- src/containers/LMS/LTI/Activity/index.js
Changed our logic to react to new custom curriki submission verb
> CUR-934 CUR-933

- src/components/Header/index.js
- src/containers/Auth/SubscribePage.js
Previous Behaviour: After the first login, the user will be shown a Terms and condition component but it was with header and sidebar
Current Behaviour: Only the terms and condition component will be shown after the first login and you can go into the website only by accepting it.
> CUR-949:Remove header, sidebar from T&C component

- src/containers/App/index.js
fixed demo preview for memory card activity
> fixed demo preview for memory card activity

- package-lock.json
- package.json
- src/components/models/GoogleLoginModal.js
- src/components/models/styles.scss
- src/containers/Auth/LoginPage.js
- src/containers/Auth/style.scss
* model changes
* more changes
> Feature/merge model changes (#516)

- src/containers/Admin/index.js
- src/containers/Admin/starter.js
- src/containers/Admin/table.js
- src/containers/Admin/userroles.js
- src/containers/Projects/ProjectCard/index.js
- src/services/organizations.services.js
- src/store/actions/organization.js
> Feature/pagination scroll (#518)

- package-lock.json
- package.json
- src/containers/Admin/formik/createuser.js
- src/containers/ManageOrganization/addUser.js
⦁	CUR-1583
⦁	CUR-1655
⦁	CUR-1580
> Admin Panel QA Tickets

- src/containers/Admin/formik/createActivityItem.js
- src/containers/Admin/index.js
- src/containers/Admin/pills.js
- src/containers/ManageOrganization/addUser.js
- src/utils/index.js
⦁	CUR-1659
⦁	CUR-1664
⦁	CUR-1662
⦁	CUR-1663
> QA Tickets

- src/containers/Admin/controler.js
- src/containers/Admin/formik/createOrg.js
- src/containers/Admin/pills.js
- src/containers/Admin/starter.js
- src/containers/Admin/table.js
- src/containers/Auth/RegisterPage.js
- src/store/actions/organization.js
- src/utils/index.js
⦁	CUR-1524
⦁	CUR-1685
⦁	CUR-1642
⦁	CUR-1695
⦁	CUR-1694
⦁	CUR-1690
⦁	CUR-1689
⦁	CUR-1683 (On Register Page)
⦁	CUR-1680
⦁      One Type fixed on register page
> QA Testing

- src/components/ResourceCard/ResourceCardDropdown.js
- src/components/Sidebar/index.js
- src/containers/Admin/pills.js
- src/containers/Projects/ProjectCard/index.js
- src/services/admin.service.js
- src/store/actions/admin.js
- src/store/actions/organization.js
⦁	CUR-1714
⦁	CUR-1709
⦁	CUR-1713
⦁	CUR-1446
⦁	CUR-1240
⦁	CUR-1716
⦁	CUR-1690 (Improved)
⦁	CUR-1695 (Improved)
⦁	Blank Screen fix
⦁	CUR-1567
⦁	CUR-1711
> QA Tickets & Bugs

- src/components/InviteDialog/index.js
- src/containers/Teams/AddMembers/index.js
- src/containers/Teams/AddProjects/index.js
- src/containers/Teams/CreateTeam/index.js
- src/containers/Teams/TeamCard/index.js
- src/containers/Teams/TeamMemberView/index.js
- src/containers/Teams/TeamProjectView/index.js
- src/containers/Teams/index.js
- src/store/actions/project.js
- src/store/actions/team.js
- Previously we were not fetching any permissions if the page reloads, now on every route of TEAM we are fetching permissions if they are missing in redux.
- Minor fixes on page reload. i.e Fetching project on page reload, Active organization was missing, added checks
> Fetch Team permissions

- src/components/Sidebar/index.js
- src/containers/Admin/column.js
- src/containers/Admin/controler.js
- src/containers/Admin/formik/editProject.js
- src/containers/Admin/pills.js
- src/containers/Admin/table.js
- src/containers/Groups/index.js
- src/containers/Groups/style.scss
- src/containers/Teams/index.js
- src/containers/Teams/style.scss
⦁	CUR-1872
⦁	CUR-1873
⦁	CUR-1862
> Mob Session Changes

- src/containers/Admin/index.js
- src/store/actions/auth.js
> State management on page refresh-> Admin Panel

- src/containers/LMS/Canvas/DeepLinking/PreviewActivity/index.js
- src/containers/LMS/Canvas/DeepLinking/Project/style.scss
- src/containers/LMS/GoogleClassroom/Activity/index.js
- src/containers/LMS/LTI/Activity/index.js
- src/services/safelearn.service.js
- xAPI sequence changes to canvas integration
- Learnsafe changes to gclass and canvas integrations
- Deeplinking search styling changes
> Merging from develop

- src/containers/Preview/ProjectPreview/index.js
- src/services/playlist.service.js
- src/store/actions/playlist.js
Added extra parameter to playlist service to skip h5p content when requesting the playlist activities
> CUR-1969 request optimization

- src/containers/LMS/GoogleClassroom/Activity/index.js
- src/services/gapi.service.js
- src/store/actions/gapi.js
Added submission ID to h5p settings call in google classroom activities in order to better support data persistence features
> Added submission ID to h5p settings call

- src/containers/Admin/formik/createuser.js
- src/containers/Admin/formik/createuser.scss
- src/containers/Admin/pills.js
- src/services/organizations.services.js
- src/store/actions/organization.js
> CUR-2554 Sub tasks

- src/containers/Preview/ProjectPreview/ProjectPreviewShared.js
CUR-3248 QA issue mentioned is fixed in this PR
> project not shareable issue fixed

- src/containers/H5PPreview.js
There was an error with activities not displaying when you go through the shared project link pathway. Also pulled in the latest version of H5PPreview.js from dev since it has other important fixes that were not here
> Shared project link fixes

- src/containers/Preview/PlaylistPreview/ActivityShared.js
- src/containers/Search/index.js
- src/services/resource.service.js
- src/store/actions/resource.js
…iveLearningStudio-react-client into CUR-3783-ui-changes-to-search-ui-to-include-independent-activity-tab
> preview added

- src/assets/css/dynamicBranding.css
- src/containers/Admin/formik/createOrg.js
> FIX:fix fonts

- src/containers/Teams/TeamDetailView/index.js
- src/containers/Teams/TeamDetailView/style.scss
> FIX:fix style issue in team detail

- src/containers/LMS/Canvas/DeepLinking/ActivitiesList/index.js
Reverts ActiveLearningStudio/ActiveLearningStudio-react-client#1376
> Revert "[CUR-4082] Deeplinking issue with ind activities"

- src/helpers/xapi.js
Reverts ActiveLearningStudio/ActiveLearningStudio-react-client#1379
> Revert "Whitelist URL for independent activity in xApi"

- src/containers/Search/index.js
> FIX:search page pagination fixed

- src/store/reducers/admin.js
> FIX:fixing issue 9

- src/assets/css/dynamicBranding.css
- src/assets/images/Iconlibrary/chevron_down_sm.svg
- src/assets/images/Iconlibrary/chevron_right_sm.svg
- src/assets/images/Iconlibrary/close_sm.svg
- src/assets/images/Iconlibrary/square_check_sm.svg
- src/assets/images/Iconlibrary/square_sm.svg
- src/iconLibrary/mainContainer/ChevronDownSmSvg.js
- src/iconLibrary/mainContainer/ChevronRightSmSvg.js
- src/iconLibrary/mainContainer/CloseSmSvg.js
- src/iconLibrary/mainContainer/SearchSmSvg.js
- src/iconLibrary/mainContainer/SquareCheckSmSvg.js
- src/iconLibrary/mainContainer/SquareSmSvg.js
- src/utils/SelectImage/SmithsonianAccordion.js
- src/utils/SelectImage/SmithsonianFilter.js
- src/utils/SelectImage/modal.js
- src/utils/SelectImage/pexels.js
- src/utils/SelectImage/style.scss
update smith filter and model branding
> FEAT:update smith filter and model branding

- src/containers/Search/CloneModel.js
- src/containers/Search/style.scss
- src/containers/Videos/formik/addvideo.js
- src/containers/Videos/formik/describevideo.js
- src/containers/Videos/index.js
- src/containers/Videos/style.scss
- src/utils/SelectImage/modal.js
> FEAT:Adding new features

- src/containers/Admin/pills.js
Update issue fixed is LMS Setting tab
> FIX:Updating the issue fixed

- src/containers/Admin/media.js
- src/store/reducers/admin.js
> FIX:lti and media tab fix

- src/services/search.service.js
- src/store/actions/share.js
CUR 4413 show response msg coming from API
> CUR 4413 show response msg coming from API

- src/containers/Admin/column.js
- src/containers/Admin/media.js
- src/containers/Admin/table.js
> FIX:Update design

- src/containers/Admin/formik/createOrg.js
- src/containers/Admin/style.scss
- src/containers/Admin/table.js
- src/containers/Playlists/index.js
> FIX:Update lib pref

- src/containers/RecordVideo/pageHeadline.js
- src/containers/RecordVideo/style.scss
- src/containers/Videos/formik/describevideo.js
- src/utils/KomodoCard/komodocard.js
update  record and activity page
> FEAT:update  record and activty page

- src/containers/Preview/PlaylistPreview/ActivityShared.js
> FIX:style issue

- src/containers/Account/style.scss
> FIX:Fixing account page style

- nginx.conf
CUR 4554 increasing the limit of max request length
> CUR 4554 increasing the limit of max request length

- .vscode/settings.json
- src/containers/Admin/formik/createActivityLayout.js
- src/containers/Admin/formik/createAuthorTag.js
- src/containers/Admin/formik/createEducationLevel.js
- src/containers/Admin/pills.js
> FIX: Ref table Tabs

- src/containers/Admin/formik/createOrg.js
- src/iconLibrary/mainContainer/ResetSmSvg.js
- src/store/actions/organization.js
> FEAT:adding auto approval

- src/containers/Videos/index.js
User tour tooltip in activity page
> FEAT:update the user tour in activity page

- src/containers/Admin/pills.js
- src/containers/Search/index.js
> [CUR-4745] add filter on admin panel projects activities

- src/containers/Preview/PlaylistPreview/index.js
- src/utils/AddVideoCard/addvideocard.js
> [CUR-4727] special character issue fix
